# Generated by Django 4.2.13 on 2026-03-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_customuser_account_name_customuser_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='account_name',
            new_name='bank_account_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='account_number',
            new_name='bank_account_number',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='nssf_number',
            new_name='nssf_no',
        ),
    ]
