# Generated by Django 4.2.13 on 2026-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_rename_account_name_customuser_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deduction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
