# Generated by Django 4.2.13 on 2026-03-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_customuser_deduction_amount_alter_customuser_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nssf_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly NSSF deduction amount', max_digits=12, null=True),
        ),
    ]
