# Generated by Django 4.2.13 on 2026-04-19 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userofficeassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salary',
            name='fund_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.office'),
        ),
        migrations.AddField(
            model_name='salary',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officetransaction',
            name='office_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.office'),
        ),
        migrations.AddField(
            model_name='officetransaction',
            name='office_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='app.office'),
        ),
        migrations.AddField(
            model_name='officetransaction',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='office',
            name='head_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_offices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nyongeza',
            name='Office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.office'),
        ),
        migrations.AddField(
            model_name='nyongeza',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_nyongezas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loantopup',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='app.loanapplication'),
        ),
        migrations.AddField(
            model_name='loantopup',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_topups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='app.loanapplication'),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_repayments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='app.client'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hqtransaction',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hq_transactions_from', to='app.office'),
        ),
        migrations.AddField(
            model_name='hqtransaction',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hqtransaction',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hq_transactions_to', to='app.office'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.expensecategory'),
        ),
        migrations.AddField(
            model_name='client',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='registered_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_registered', to='app.office'),
        ),
        migrations.AddField(
            model_name='branchbalance',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_balances', to='app.office'),
        ),
        migrations.AddField(
            model_name='branchbalance',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankcharge',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_charge_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankcashtransaction',
            name='office_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_bank_cash', to='app.office'),
        ),
        migrations.AlterUniqueTogether(
            name='userofficeassignment',
            unique_together={('user', 'office')},
        ),
        migrations.AlterUniqueTogether(
            name='branchbalance',
            unique_together={('branch', 'last_updated')},
        ),
    ]
