# Generated by Django 4.2.13 on 2026-02-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
