# Generated by Django 4.2.13 on 2026-02-04 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
