# Generated by Django 4.2.13 on 2026-02-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_loanapplication_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmortizationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('principal_repayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_repayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortization_schedule', to='app.loanapplication')),
            ],
            options={
                'ordering': ['installment_number'],
                'indexes': [models.Index(fields=['loan_application', 'installment_number'], name='app_amortiz_loan_ap_761e01_idx'), models.Index(fields=['due_date', 'is_paid'], name='app_amortiz_due_dat_27b47f_idx')],
            },
        ),
    ]
