# Generated by Django 4.2.13 on 2026-02-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_amortizationschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmortizationSchedule',
        ),
    ]
