# Generated by Django 4.2.13 on 2026-02-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_amortizationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expense_attachments/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
