# Generated by Django 4.2.13 on 2026-02-23 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_banktransaction_bankcashtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='officetransaction',
            name='processed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='processed_transactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
