# Generated by Django 4.2.13 on 2026-02-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_bankamount_delete_banktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankamount',
            name='office',
        ),
        migrations.RemoveField(
            model_name='bankamount',
            name='total_deposits',
        ),
    ]
