# Generated by Django 4.2.13 on 2026-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_loantopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantopup',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
