# Generated by Django 4.2.13 on 2026-02-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_hqtransaction_branchbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='nyongeza',
            name='Office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.office'),
        ),
        migrations.AddField(
            model_name='nyongeza',
            name='deposit_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='transaction_method',
            field=models.CharField(blank=True, default='bank', max_length=100, null=True),
        ),
    ]
