# Generated by Django 4.2.13 on 2026-02-26 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_nyongeza_office_nyongeza_deposit_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='fund_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.office'),
        ),
    ]
