# Generated by Django 4.2.13 on 2026-02-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_salary_fund_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='transaction_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
