# Generated by Django 4.2.13 on 2026-02-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_loanrepayment_transaction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantopup',
            name='transaction_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
