# Generated by Django 4.2.13 on 2026-02-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_loantopup_transaction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(default='Approved', max_length=50),
        ),
    ]
