# Generated by Django 4.2.13 on 2026-02-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_loanapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nyongeza',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
