# Generated by Django 4.2.13 on 2026-02-27 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0031_alter_nyongeza_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expense_attachments/')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_charge_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
