# Generated by Django 4.2.13 on 2026-03-01 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0034_alter_officetransaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='Salary Advance', help_text='Type of deduction account e.g. Salary Advance, Loan, etc.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total loan/advance amount', max_digits=15)),
                ('payment_period', models.PositiveIntegerField(help_text='Number of months to repay')),
                ('starting_payment_month', models.DateField(help_text='First month deduction begins (stored as 1st of that month)')),
                ('ending_payment_month', models.DateField(blank=True, help_text='Last month of deduction (auto-calculated)', null=True)),
                ('monthly_installment', models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: amount / payment_period', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Advance',
                'verbose_name_plural': 'Salary Advances',
                'ordering': ['-created_at'],
            },
        ),
    ]
