# Generated by Django 4.2.13 on 2026-03-09 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_loanapplication_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='office_dealing', to='app.office'),
            preserve_default=False,
        ),
    ]
