# Generated by Django 4.2.13 on 2026-03-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_loanapplication_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
