# Generated by Django 4.2.13 on 2026-03-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_hqtransaction_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcashtransaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='bank_cash_attachments/'),
        ),
        migrations.AddField(
            model_name='hqtransaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='hq_transaction_attachments/'),
        ),
        migrations.AddField(
            model_name='officetransaction',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='office_transaction_attachments/'),
        ),
    ]
