# Generated by Django 4.2.13 on 2026-03-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_bankcashtransaction_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='payment_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loantopup',
            name='payment_month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
