# Generated by Django 4.2.13 on 2026-02-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('middlename', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('employername', models.CharField(blank=True, max_length=255, null=True)),
                ('idara', models.CharField(blank=True, max_length=255, null=True)),
                ('kaziyako', models.CharField(blank=True, max_length=255, null=True)),
                ('employmentcardno', models.CharField(blank=True, max_length=255, null=True)),
                ('tareheya_kuajiriwa', models.DateField(blank=True, null=True)),
                ('umri_kazini', models.IntegerField(blank=True, null=True)),
                ('tarehe_ya_kustaafu', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('checkno', models.CharField(blank=True, max_length=255, null=True)),
                ('mkoa', models.CharField(blank=True, max_length=255, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=255, null=True)),
                ('tarafa', models.CharField(blank=True, max_length=255, null=True)),
                ('kata', models.CharField(blank=True, max_length=255, null=True)),
                ('mtaa', models.CharField(blank=True, max_length=255, null=True)),
                ('wategemezi_wako', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_type', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('registered_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
