# Generated by Django 4.2.13 on 2026-02-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_client_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('office_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.office')),
                ('office_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='app.office')),
            ],
        ),
    ]
