# Generated by Django 4.2.13 on 2026-02-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='first_repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
