# Generated by Django 4.2.13 on 2026-02-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_loanapplication_first_repayment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
