# Generated by Django 4.2.13 on 2026-02-26 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0021_expensecategory_alter_expense_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topup_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('topup_date', models.DateField(auto_now_add=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='app.loanapplication')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_topups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
