# Generated by Django 4.2.13 on 2026-02-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_bankcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='officetransaction',
            name='transaction_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
