# Generated by Django 4.2.13 on 2026-02-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_officetransaction_transaction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
