# Generated by Django 4.2.13 on 2026-03-02 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0035_salaryadvance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOfficeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='app.office')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('user', 'office')},
            },
        ),
    ]
