# Generated by Django 4.2.13 on 2026-03-03 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_userofficeassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='registered_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_registered', to='app.office'),
        ),
    ]
