# Generated by Django 4.2.13 on 2026-03-09 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_client_registered_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loantopup',
            name='old_balance_cleared',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='application_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
