# Generated by Django 4.2.13 on 2026-03-09 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_loanapplication_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='hqtransaction',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hqtransaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
