# Generated by Django 4.2.13 on 2026-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_loanrepayment_payment_month_loantopup_payment_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loantopup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
