# Generated by Django 4.2.13 on 2026-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_bankcharge_created_at_expense_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='repayment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
